import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  build: {
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'ProDocCli',
      fileName: 'index',
      formats: ['es'],
    },
    rollupOptions: {
      external: [
        // Node.js built-ins
        'fs',
        'fs/promises',
        'path',
        'url',
        'child_process',
        'process',
        'readline',
        'http',
        'https',
        'os',
        'crypto',
        'util',
        'tty',
        'net',
        'events',
        'stream',
        'zlib',
        'querystring',
        'buffer',
        'assert',
        'node:fs',
        'node:fs/promises',
        'node:path',
        'node:url',
        'node:child_process',
        'node:process',
        'node:readline',
        'node:http',
        'node:https',
        'node:os',
        'node:crypto',
        'node:util',
        'node:tty',
        'node:net',
        'node:events',
        'node:stream',
        'node:zlib',
        'node:querystring',
        'node:buffer',
        'node:assert',
        'node:perf_hooks',
        'node:module',
        'module',
        'node:http2',
        // Dependencies — resolved at runtime via node_modules
        'vite',
        '@vitejs/plugin-vue',
        'vue',
        '@prodoc/core',
        '@prodoc/renderer',
        '@prodoc/editor',
        'marked',
      ],
    },
    sourcemap: true,
  },
});
